# Generated by Django 3.2.5 on 2021-07-28 04:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('domain', models.URLField(blank=True, null=True)),
                ('url', models.URLField(null=True)),
                ('scan_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('timezone', models.CharField(max_length=255, null=True)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('page_content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchDomain',
            fields=[
                ('domain_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=100)),
                ('ts', models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 28, 4, 49, 46, 274169))),
                ('keywords', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
