# Generated by Django 3.2.5 on 2021-07-28 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdomain',
            name='ts',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 28, 5, 26, 23, 631458)),
        ),
    ]
