# Generated by Django 3.2.5 on 2021-07-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_searchdomain_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='screenshot_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchdomain',
            name='ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
