# Generated by Django 3.2.5 on 2021-07-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210730_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='task_id',
        ),
        migrations.AddField(
            model_name='searchdomain',
            name='task_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
