# Generated by Django 3.2.5 on 2021-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210730_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdomain',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
