# Generated by Django 3.2.5 on 2021-08-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_searchdomain_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='domain',
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='domain_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
