# Generated by Django 3.2.5 on 2021-08-01 04:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210801_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputPeter',
            fields=[
                ('domain_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=100)),
                ('ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.UUIDField(null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='domain_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='main.searchdomain'),
        ),
        migrations.CreateModel(
            name='OutputPeter',
            fields=[
                ('url_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField(null=True)),
                ('scan_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('page_content', models.TextField(null=True)),
                ('screenshot_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inputpeter')),
            ],
        ),
    ]
