# Generated by Django 3.2.5 on 2021-08-01 06:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210801_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputMary',
            fields=[
                ('input_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now=True, db_index=True)),
                ('pw_product', models.CharField(max_length=100)),
                ('merchant_id', models.PositiveIntegerField(blank=True, null=True)),
                ('merchant_name', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputMary',
            fields=[
                ('url_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField(null=True)),
                ('merdchant_url', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('page_content', models.TextField(null=True)),
                ('screenshot_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('input_id', models.ForeignKey(db_column='input_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='main.inputmary')),
            ],
        ),
    ]
