# Generated by Django 3.2.5 on 2021-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_inputmary_outputmary'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputmary',
            name='task_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
