# Generated by Django 3.2.5 on 2021-08-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_inputmary_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputmary',
            old_name='merdchant_url',
            new_name='merchant_url',
        ),
    ]
