# Generated by Django 3.2.5 on 2021-08-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_merdchant_url_outputmary_merchant_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='SearchDomain',
        ),
    ]
