# Generated by Django 3.2.5 on 2021-08-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_inputmary_pw_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmary',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inputmary',
            name='pw_product',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='outputmary',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outputmary',
            name='pw_product',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
